# Generated by Django 4.0.6 on 2022-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('owned', models.BooleanField(default=False)),
                ('secret_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('owned_cars', models.ManyToManyField(blank=True, to='database.car')),
            ],
        ),
    ]
