# Generated by Django 4.0.6 on 2022-07-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_nftcar_picture_user_languge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
