# Generated by Django 4.0.6 on 2022-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_nftcar_paid_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcar',
            name='owner_addr',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
