# Generated by Django 4.0.6 on 2022-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_nftcar_owner_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcar',
            name='owner_addr',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
