# Generated by Django 4.0.6 on 2022-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_nftcar_owner_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcar',
            name='token_id',
            field=models.CharField(max_length=255),
        ),
    ]
