# Generated by Django 4.0.6 on 2022-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_user_last_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languge',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'En'), ('it', 'It'), ('ru', 'Ru')], default='en', max_length=2),
        ),
    ]
